In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('DelhiAQI.csv')

In [3]:
data.head()

PM2.5    PM10      NO    NO2     NOx    NH3     CO   SO2     O3  Benzene  \
0  454.58  935.18   81.52  41.78  187.66  27.54   9.29  3.41  54.94    25.24   
1  440.44  935.18   70.80  43.46  176.83  27.72  13.28  3.88  50.53    23.10   
2  409.09  935.18  132.46  41.19  141.02  28.94  29.67  2.83  19.33    19.04   
3  436.12  935.18   84.78  39.55  102.84  29.30  21.76  4.33  20.08    13.99   
4  415.88  976.99   60.24  37.41   80.12  30.84  26.19  6.17  16.00    11.14   

   Toluene  Xylene  AQI  
0    58.57   13.80  653  
1    49.37   15.63  645  
2    38.94   17.18  532  
3    27.53   16.82  561  
4    21.99   14.29  567

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)
data_scaled

array([[ 4.42588175,  5.27561435,  1.07934007, ...,  4.19721961,
         3.17072104,  3.87542458],
       [ 4.24239721,  5.27561435,  0.83951094, ...,  3.37699166,
         3.65270076,  3.79199029],
       [ 3.83559097,  5.27561435,  2.21897586, ...,  2.44710279,
         4.06093494,  2.61348099],
       ...,
       [-0.81199194, -0.35107535, -0.3312221 , ..., -0.12324198,
        -0.45861257, -0.94290547],
       [-0.57465586, -0.31231054, -0.30437556, ..., -0.39873159,
        -0.46388011, -0.96376405],
       [-0.55726765, -0.24918776, -0.34710631, ..., -0.33810605,
        -0.46388011, -0.96376405]])

In [5]:
train_size = int(0.6 * len(data_scaled))
val_size = int(0.2 * len(data_scaled))
test_size = len(data_scaled) - train_size - val_size

X_train, y_train = data_scaled[:train_size, :-1], data_scaled[:train_size, -1]
X_val, y_val = data_scaled[train_size:train_size+val_size, :-1], data_scaled[train_size:train_size+val_size, -1]
X_test, y_test = data_scaled[train_size+val_size:, :-1], data_scaled[train_size+val_size:, -1]


In [6]:
# Fit the scaler on the training data only and transform the training, validation, and test sets
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)


In [7]:
X_train

array([[ 4.19602887,  5.06772012,  1.06443688, ...,  5.92959982,
         4.34772925,  2.39477984],
       [ 4.01767733,  5.06772012,  0.82132007, ...,  5.3390256 ,
         3.5082145 ,  2.79811038],
       [ 3.62225152,  5.06772012,  2.21969529, ...,  4.21859038,
         2.55646029,  3.13972914],
       ...,
       [ 2.01103327,  1.54038735,  4.54495335, ...,  1.3926651 ,
         1.28532546, -0.64232114],
       [ 2.38905277,  1.83959148,  4.97857214, ...,  1.5444482 ,
         1.43954067, -0.64672913],
       [ 2.33973491,  1.44887893,  4.27462197, ...,  1.46441711,
         1.43497809, -0.64672913]])

In [8]:
X_val

array([[ 2.01229459,  1.42463684,  2.67826077, ...,  1.35126971,
         1.4979417 , -0.64672913],
       [ 1.93283103,  1.64769316,  3.17220518, ...,  1.35126971,
         1.52440466, -0.64672913],
       [ 1.99123044,  1.54686646,  3.12956902, ...,  1.28503709,
         1.40395255, -0.64672913],
       ...,
       [ 1.13113202,  3.71322084,  2.82726053, ...,  3.5700626 ,
         5.07500452, -0.64232114],
       [ 1.57801994,  2.56940203,  5.00170452, ...,  4.80916461,
         4.90710157, -0.64672913],
       [ 0.99352131,  3.36407655,  3.51646946, ...,  5.14308742,
         5.02025356, -0.64672913]])

In [9]:
X_test

array([[ 0.58384252,  3.11597736,  4.25670572, ...,  5.0740951 ,
         4.78026185, -0.64672913],
       [ 1.02707259,  3.24097335,  3.40534331, ...,  4.76500952,
         4.39335505, -0.64672913],
       [ 0.65523359,  0.69118633,  1.69604165, ...,  4.90575385,
         4.3678046 , -0.64672913],
       ...,
       [-0.89531487, -0.44811893, -0.36546189, ..., -0.10032863,
        -0.07432342, -0.64232114],
       [-0.66461828, -0.41011782, -0.33824732, ..., -0.35146066,
        -0.35629087, -0.64672913],
       [-0.64771651, -0.34823862, -0.38156384, ..., -0.38181728,
        -0.29423978, -0.64672913]])

In [10]:
data_scaled.size

195000

In [11]:
X_train.size

108000

In [12]:
X_val.size

36000

In [13]:
X_test.size

36000

In [14]:
from sklearn.model_selection import train_test_split
X = data.drop(columns=['AQI'])
y = data['AQI']

scaler = StandardScaler()
X_normalized = scaler.fit_transform(X)

X_train, X_temp, y_train, y_temp = train_test_split(X_normalized, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [15]:
import tensorflow as tf
from sklearn.svm import SVR
from sklearn.decomposition import PCA
from sklearn.metrics import mean_squared_error

In [27]:
# class Dense(Layer):
# ...
#     def __init__(self, units,
#                  activation=None,
#                  use_bias=True,
#                  kernel_initializer='glorot_uniform',
#                  bias_initializer='zeros',
#                  kernel_regularizer=None,
#                  bias_regularizer=None,
#                  activity_regularizer=None,
#                  kernel_constraint=None,
#                  bias_constraint=None,
#                  **kwargs):

#  keras uses Glorot initialization with a uniform distribution.r = √(3/fan_avg)

def build_model_1():
    model = models.Sequential([
        layers.Dense(32, activation='sigmoid', kernel_initializer='glorot_uniform', input_shape=(X_train.shape[1],)),
        layers.Dense(16, activation='relu', kernel_initializer='he_uniform'),
        layers.Dense(1, activation='relu', kernel_initializer='he_uniform')
    ])
    model.compile(optimizer=optimizers.Adam(learning_rate=0.01), loss='mse')
    return model


In [28]:
def build_model_2():
    model = models.Sequential([
        layers.Dense(32, activation='sigmoid', kernel_initializer='glorot_uniform', input_shape=(X_train.shape[1],)),
        layers.Dense(8, activation='sigmoid', kernel_initializer='glorot_normal'),
        layers.Dense(1, activation='relu', kernel_initializer='he_uniform')
    ])
    model.compile(optimizer=optimizers.Adam(learning_rate=0.01), loss='mse')
    return model

In [18]:
def train_model(model, batch_size, epochs):
    model.fit(X_train, y_train, validation_data=(X_val, y_val), batch_size=batch_size, epochs=epochs, verbose=0)
    return model


In [19]:
from tensorflow.keras import layers, models, optimizers
def evaluate_model(build_model_fn, batch_size, epochs, layer_to_extract):
    rmses = []
    for _ in range(5):
        model = train_model(build_model_fn(), batch_size, epochs)
        
        y_pred = model.predict(X_test).flatten()

        y_pred_denorm = y_pred * scaler.scale_[-1] + scaler.mean_[-1]
        y_test_denorm = y_test * scaler.scale_[-1] + scaler.mean_[-1]
        
        rmse = compute_rmse(y_test_denorm, y_pred_denorm)
        rmses.append(rmse)
    
    return np.mean(rmses)

In [20]:
def train_svr(X, y):
    svr = SVR(kernel='rbf')
    svr.fit(X, y)
    return svr

In [21]:
def extract_features(model, X, layer_index):
    feature_extractor = models.Model(inputs=model.input, outputs=model.layers[layer_index].output)
    return feature_extractor.predict(X)

In [22]:
def apply_pca(X, n_components):
    pca = PCA(n_components=n_components)
    return pca.fit_transform(X)

In [23]:
def compute_rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

In [24]:
rmse_model_1 = evaluate_model(build_model_1, batch_size=16, epochs=20, layer_to_extract=1)
print(f'Mean RMSE for Model-1: {rmse_model_1}')

rmse_model_2 = evaluate_model(build_model_2, batch_size=8, epochs=20, layer_to_extract=1)
print(f'Mean RMSE for Model-2: {rmse_model_2}')

C:\Python 311\New folder\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


C:\Python 311\New folder\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


C:\Python 311\New folder\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


C:\Python 311\New folder\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


C:\Python 311\New folder\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Mean RMSE for Model-1: 388.01187393364586


C:\Python 311\New folder\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


C:\Python 311\New folder\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


C:\Python 311\New folder\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


C:\Python 311\New folder\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


C:\Python 311\New folder\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Mean RMSE for Model-2: 576.0717450010847


In [25]:
def evaluate_model_3():
    model_1 = train_model(build_model_1(), batch_size=16, epochs=20)
    model_2 = train_model(build_model_2(), batch_size=8, epochs=20)
    
    features_model_1 = extract_features(model_1, X_train, 1)  
    features_model_2 = extract_features(model_2, X_train, 1) 
    
    combined_features = np.hstack((features_model_1, features_model_2))
    
    svr = train_svr(combined_features, y_train)
    y_pred = svr.predict(np.hstack((extract_features(model_1, X_test, 1), extract_features(model_2, X_test, 1))))
    
    y_pred_denorm = y_pred * scaler.scale_[-1] + scaler.mean_[-1]
    y_test_denorm = y_test * scaler.scale_[-1] + scaler.mean_[-1]
    
    return compute_rmse(y_test_denorm, y_pred_denorm)

In [29]:
rmse_model_3 = evaluate_model_3()
print(f'Mean RMSE for Model-3: {rmse_model_3}')

ValueError: The layer sequential_12 has never been called and thus has no defined input.

In [30]:
def evaluate_model_4(n_components):
    model_1 = train_model(build_model_1(), batch_size=16, epochs=20)
    model_2 = train_model(build_model_2(), batch_size=8, epochs=20)
    
    features_model_1 = extract_features(model_1, X_train, 1)  
    features_model_2 = extract_features(model_2, X_train, 1)  
    
    combined_features = np.hstack((features_model_1, features_model_2))
    
    reduced_features = apply_pca(combined_features, n_components=n_components)
    
    svr = train_svr(reduced_features, y_train)
    y_pred = svr.predict(apply_pca(np.hstack((extract_features(model_1, X_test, 1), extract_features(model_2, X_test, 1))), n_components))
    
    y_pred_denorm = y_pred * scaler.scale_[-1] + scaler.mean_[-1]
    y_test_denorm = y_test * scaler.scale_[-1] + scaler.mean_[-1]
    
    return compute_rmse(y_test_denorm, y_pred_denorm)

In [31]:
rmse_model_4_8 = evaluate_model_4(n_components=8)
rmse_model_4_10 = evaluate_model_4(n_components=10)
rmse_model_4_12 = evaluate_model_4(n_components=12)

print(f'Mean RMSE for Model-4 (8 components): {rmse_model_4_8}')
print(f'Mean RMSE for Model-4 (10 components): {rmse_model_4_10}')
print(f'Mean RMSE for Model-4 (12 components): {rmse_model_4_12}')

ValueError: The layer sequential_14 has never been called and thus has no defined input.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.decomposition import PCA
from sklearn.metrics import mean_squared_error
import tensorflow as tf
from tensorflow.keras import layers, models, optimizers

data = pd.read_csv('./DelhiAQI.csv')

X = data.drop(columns=['AQI'])
y = data['AQI']

scaler = StandardScaler()
X_normalized = scaler.fit_transform(X)

X_train, X_temp, y_train, y_temp = train_test_split(X_normalized, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

def build_model_1():
    model = models.Sequential([
        layers.Dense(32, activation='sigmoid', kernel_initializer='glorot_uniform', input_shape=(X_train.shape[1],)),
        layers.Dense(16, activation='relu', kernel_initializer='he_uniform'),
        layers.Dense(1, activation='relu', kernel_initializer='he_uniform')
    ])
    model.compile(optimizer=optimizers.Adam(learning_rate=0.01), loss='mse')
    return model

def build_model_2():
    model = models.Sequential([
        layers.Dense(32, activation='sigmoid', kernel_initializer='glorot_uniform', input_shape=(X_train.shape[1],)),
        layers.Dense(8, activation='sigmoid', kernel_initializer='glorot_normal'),
        layers.Dense(1, activation='relu', kernel_initializer='he_uniform')
    ])
    model.compile(optimizer=optimizers.Adam(learning_rate=0.01), loss='mse')
    return model

def train_model(model, batch_size, epochs):
    model.fit(X_train, y_train, validation_data=(X_val, y_val), batch_size=batch_size, epochs=epochs, verbose=0)
    return model

def extract_features(model, X, layer_index):
    feature_extractor = models.Model(inputs=model.input, outputs=model.layers[layer_index].output)
    return feature_extractor.predict(X)

def train_svr(X, y):
    svr = SVR(kernel='rbf')
    svr.fit(X, y)
    return svr

def apply_pca(X, n_components):
    pca = PCA(n_components=n_components)
    return pca.fit_transform(X)

def compute_rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

def evaluate_model(build_model_fn, batch_size, epochs, layer_to_extract):
    rmses = []
    for _ in range(5):
        model = train_model(build_model_fn(), batch_size, epochs)
        
        y_pred = model.predict(X_test).flatten()

        y_pred_denorm = y_pred * scaler.scale_[-1] + scaler.mean_[-1]
        y_test_denorm = y_test * scaler.scale_[-1] + scaler.mean_[-1]
        
        rmse = compute_rmse(y_test_denorm, y_pred_denorm)
        rmses.append(rmse)
    
    return np.mean(rmses)

rmse_model_1 = evaluate_model(build_model_1, batch_size=16, epochs=20, layer_to_extract=1)
print(f'Mean RMSE for Model-1: {rmse_model_1}')

rmse_model_2 = evaluate_model(build_model_2, batch_size=8, epochs=20, layer_to_extract=1)
print(f'Mean RMSE for Model-2: {rmse_model_2}')

def evaluate_model_3():
    model_1 = train_model(build_model_1(), batch_size=16, epochs=20)
    model_2 = train_model(build_model_2(), batch_size=8, epochs=20)
    
    features_model_1 = extract_features(model_1, X_train, 1)  
    features_model_2 = extract_features(model_2, X_train, 1) 
    
    combined_features = np.hstack((features_model_1, features_model_2))
    
    svr = train_svr(combined_features, y_train)
    y_pred = svr.predict(np.hstack((extract_features(model_1, X_test, 1), extract_features(model_2, X_test, 1))))
    
    y_pred_denorm = y_pred * scaler.scale_[-1] + scaler.mean_[-1]
    y_test_denorm = y_test * scaler.scale_[-1] + scaler.mean_[-1]
    
    return compute_rmse(y_test_denorm, y_pred_denorm)

rmse_model_3 = evaluate_model_3()
print(f'Mean RMSE for Model-3: {rmse_model_3}')

def evaluate_model_4(n_components):
    model_1 = train_model(build_model_1(), batch_size=16, epochs=20)
    model_2 = train_model(build_model_2(), batch_size=8, epochs=20)
    
    features_model_1 = extract_features(model_1, X_train, 1)  
    features_model_2 = extract_features(model_2, X_train, 1)  
    
    combined_features = np.hstack((features_model_1, features_model_2))
    
    reduced_features = apply_pca(combined_features, n_components=n_components)
    
    svr = train_svr(reduced_features, y_train)
    y_pred = svr.predict(apply_pca(np.hstack((extract_features(model_1, X_test, 1), extract_features(model_2, X_test, 1))), n_components))
    
    y_pred_denorm = y_pred * scaler.scale_[-1] + scaler.mean_[-1]
    y_test_denorm = y_test * scaler.scale_[-1] + scaler.mean_[-1]
    
    return compute_rmse(y_test_denorm, y_pred_denorm)

rmse_model_4_8 = evaluate_model_4(n_components=8)
rmse_model_4_10 = evaluate_model_4(n_components=10)
rmse_model_4_12 = evaluate_model_4(n_components=12)

print(f'Mean RMSE for Model-4 (8 components): {rmse_model_4_8}')
print(f'Mean RMSE for Model-4 (10 components): {rmse_model_4_10}')
print(f'Mean RMSE for Model-4 (12 components): {rmse_model_4_12}')
